/*
 * D3D8 vertex-shader handle ownership.
 *
 * D3D8 overloads SetVertexShader: values through 0xf0000000 are FVF codes,
 * while created shaders are opaque handles above that boundary. The guest
 * keeps those handles, so every slot carries a generation; deleting and then
 * reusing a slot cannot make an old handle silently name a different shader.
 */
#include "d3d8_vertex_shader_internal.h"

#include "d3d8_state.h"

#include <math.h>
#include <stdio.h>
#include <string.h>

static D3D8VertexShader g_shader[VS_MAX];
static uint16_t g_generation = 1;
static unsigned long g_created, g_deleted, g_refused;

static uint32_t make_handle(unsigned slot, uint16_t generation) {
  return VS_HANDLE_BASE + ((uint32_t)generation << 8) + slot;
}

static int scan_declaration(const uint32_t *p, uint16_t *count) {
  unsigned i;
  if (!p)
    return 0;
  for (i = 0; i < VS_DECL_MAX_DWORDS; ++i) {
    if (p[i] == 0xffffffffu) {
      *count = (uint16_t)(i + 1);
      return 1;
    }
  }
  fprintf(stderr,
          "d3d8: CreateVertexShader scanned %u declaration token(s) "
          "but found no D3DVSD_END; refusing an unterminated stream.\n",
          VS_DECL_MAX_DWORDS);
  return 0;
}

static int scan_function(const uint32_t *p, uint16_t *count) {
  unsigned i;
  if (!p) {
    *count = 0;
    return 1;
  } /* declaration-only shaders are legal */
  if (p[0] != 0xfffe0101u) {
    fprintf(stderr,
            "d3d8: CreateVertexShader function begins 0x%08x, not "
            "the VS 1.1 version token 0xfffe0101.\n",
            p[0]);
    return 0;
  }
  for (i = 1; i < VS_CODE_MAX_DWORDS; ++i) {
    if ((p[i] & 0xffffu) == 0xffffu) {
      *count = (uint16_t)(i + 1);
      return 1;
    }
  }
  fprintf(stderr,
          "d3d8: CreateVertexShader scanned %u bytecode dword(s) but "
          "found no D3DSIO_END; refusing an unterminated program.\n",
          VS_CODE_MAX_DWORDS);
  return 0;
}

uint32_t d3d8_vs_create(const uint32_t *declaration, const uint32_t *function,
                        uint32_t usage) {
  uint16_t nd, nf;
  unsigned i;
  uint32_t h;
  if (!scan_declaration(declaration, &nd) || !scan_function(function, &nf)) {
    g_refused++;
    return 0;
  }
  for (i = 0; i < VS_MAX && g_shader[i].used; ++i) {
  }
  if (i == VS_MAX) {
    fprintf(stderr,
            "d3d8: CreateVertexShader found all %u shader slots "
            "live; refusing instead of losing an existing shader.\n",
            VS_MAX);
    g_refused++;
    return 0;
  }
  memset(&g_shader[i], 0, sizeof g_shader[i]);
  g_shader[i].used = 1;
  g_shader[i].generation = g_generation++;
  if (!g_generation)
    g_generation = 1;
  g_shader[i].usage = usage;
  g_shader[i].declaration_dwords = nd;
  g_shader[i].function_dwords = nf;
  memcpy(g_shader[i].declaration, declaration, nd * sizeof *declaration);
  if (nf)
    memcpy(g_shader[i].function, function, nf * sizeof *function);
  h = make_handle(i, g_shader[i].generation);
  g_created++;
  printf("d3d8: CreateVertexShader -> 0x%08x (%u declaration token(s), "
         "%u bytecode dword(s), usage 0x%x)\n",
         h, nd, nf, usage);
  /*
   * The tokens themselves, in full.
   *
   * This executor accepts seven opcodes and refuses everything else by
   * name, so "0 draws refused" says every opcode is HANDLED -- it says
   * nothing about whether each is handled correctly, and a skinning shader
   * that computes the wrong vertex is silent by construction. Auditing the
   * interpreter against a shader nobody has read is guesswork; the shader
   * is generated by Cg at runtime and exists nowhere on disk, so this is
   * the only place it can be captured.
   *
   * A hundred-odd dwords, once per run, on a call that happens once.
   */
  {
    unsigned k;
    printf("      declaration:");
    for (k = 0; k < nd; k++)
      printf(" %08x", declaration[k]);
    printf("\n      bytecode:");
    for (k = 0; k < nf; k++)
      printf(" %08x", function[k]);
    printf("\n");
    fflush(stdout);
  }
  return h;
}

D3D8VertexShader *d3d8_vs_get(uint32_t handle, const char *operation) {
  uint32_t raw;
  unsigned slot;
  uint16_t generation;
  if (handle <= 0xf0000000u) {
    fprintf(stderr,
            "d3d8: %s received 0x%08x, an FVF value rather than a "
            "created vertex-shader handle.\n",
            operation, handle);
    g_refused++;
    return NULL;
  }
  raw = handle - VS_HANDLE_BASE;
  slot = raw & 0xffu;
  generation = (uint16_t)(raw >> 8);
  if (slot >= VS_MAX || !g_shader[slot].used ||
      g_shader[slot].generation != generation) {
    fprintf(stderr,
            "d3d8: %s received 0x%08x, which names no live vertex "
            "shader (slot %u, generation %u).\n",
            operation, handle, slot, generation);
    g_refused++;
    return NULL;
  }
  return &g_shader[slot];
}

int d3d8_vs_delete(uint32_t handle) {
  D3D8VertexShader *s = d3d8_vs_get(handle, "DeleteVertexShader");
  if (!s)
    return 0;
  s->used = 0;
  g_deleted++;
  return 1;
}

void d3d8_vs_reset(void) {
  unsigned i;
  for (i = 0; i < VS_MAX; ++i)
    g_shader[i].used = 0;
}

const uint32_t *d3d8_vs_declaration(const D3D8VertexShader *s, size_t *bytes) {
  *bytes = (size_t)s->declaration_dwords * sizeof(uint32_t);
  return s->declaration;
}

const uint32_t *d3d8_vs_function(const D3D8VertexShader *s, size_t *bytes) {
  *bytes = (size_t)s->function_dwords * sizeof(uint32_t);
  return s->function_dwords ? s->function : NULL;
}

void d3d8_vs_report(void) {
  unsigned i, live = 0;
  unsigned long executions, vertices;

  d3d8_vs_execution_counts(&executions, &vertices);

  for (i = 0; i < VS_MAX; ++i)
    if (g_shader[i].used)
      live++;
  printf("  d3d8: %lu vertex shader(s) created, %lu deleted, %u still live; "
         "%lu shader-lifecycle call(s) refused\n"
         "        VS 1.1 executor ran %lu draw(s), %lu vertex invocation(s)\n",
         g_created, g_deleted, live, g_refused, executions, vertices);
  if (g_created && !executions)
    printf("        NO created shader was executed -- this run proves the "
           "lifecycle only, not programmable drawing.\n");
  /* What the engine actually BOUND. "0 created" alone cannot tell an engine
     that wanted no shader from one that asked and was turned away. */
  d3d8_vertex_shader_binding_report();
}
