/* MSVCRT.dll and MSVCR71.dll expose the same implementations under different
 * import-module names. This owner keeps that mechanical spelling bridge out of
 * the CRT semantics and maintains one implementation for each operation. */
#include "x86rt.h"

#define CRT_ALIAS(name)                                                        \
  void imp_MSVCR71_##name(CPU *cpu);                                           \
  void imp_MSVCRT_##name(CPU *cpu) { imp_MSVCR71_##name(cpu); }

CRT_ALIAS(malloc)
CRT_ALIAS(calloc)
CRT_ALIAS(realloc)
CRT_ALIAS(memcpy)
CRT_ALIAS(memset)
CRT_ALIAS(memmove)
CRT_ALIAS(strlen)
CRT_ALIAS(strcpy)
CRT_ALIAS(strcat)
CRT_ALIAS(strcmp)
CRT_ALIAS(strchr)
CRT_ALIAS(strrchr)
CRT_ALIAS(strstr)
CRT_ALIAS(strtok)
CRT_ALIAS(strncat)
CRT_ALIAS(strncpy)
CRT_ALIAS(strncmp)
CRT_ALIAS(_strdup)
CRT_ALIAS(_stricmp)
CRT_ALIAS(_strnicmp)
CRT_ALIAS(_strlwr)
CRT_ALIAS(_strupr)
CRT_ALIAS(_itoa)
CRT_ALIAS(isalnum)
CRT_ALIAS(isalpha)
CRT_ALIAS(isdigit)
CRT_ALIAS(isspace)
CRT_ALIAS(tolower)
CRT_ALIAS(atoi)
CRT_ALIAS(atof)
CRT_ALIAS(strtod)
CRT_ALIAS(ceil)
CRT_ALIAS(floor)
CRT_ALIAS(fabs)
CRT_ALIAS(atan2)
CRT_ALIAS(exp)
CRT_ALIAS(log)
CRT_ALIAS(pow)
CRT_ALIAS(sqrt)
CRT_ALIAS(_finite)
CRT_ALIAS(_CIpow)
CRT_ALIAS(_CIfmod)
CRT_ALIAS(_CIacos)
CRT_ALIAS(_CIasin)
CRT_ALIAS(rand)
CRT_ALIAS(srand)
CRT_ALIAS(qsort)
CRT_ALIAS(fopen)
CRT_ALIAS(fclose)
CRT_ALIAS(fread)
CRT_ALIAS(fseek)
CRT_ALIAS(ftell)
CRT_ALIAS(exit)
CRT_ALIAS(_exit)
CRT_ALIAS(_purecall)
CRT_ALIAS(abort)
CRT_ALIAS(_errno)
CRT_ALIAS(getenv)
CRT_ALIAS(printf)
CRT_ALIAS(vprintf)
CRT_ALIAS(sprintf)
CRT_ALIAS(vsprintf)
CRT_ALIAS(_snprintf)
CRT_ALIAS(_vsnprintf)
CRT_ALIAS(fflush)
CRT_ALIAS(fputc)
CRT_ALIAS(fputs)
CRT_ALIAS(fgetc)
CRT_ALIAS(fgets)
CRT_ALIAS(ungetc)
CRT_ALIAS(fwrite)
CRT_ALIAS(fprintf)
CRT_ALIAS(vfprintf)
CRT_ALIAS(__2_YAPAXI_Z)
CRT_ALIAS(__3_YAXPAX_Z)
CRT_ALIAS(___V_YAXPAX_Z)
CRT_ALIAS(sscanf)
CRT_ALIAS(fscanf)
CRT_ALIAS(setlocale)
CRT_ALIAS(_onexit)
CRT_ALIAS(free)
CRT_ALIAS(_ftol)
CRT_ALIAS(_initterm)
CRT_ALIAS(_beginthreadex)
CRT_ALIAS(_endthreadex)
CRT_ALIAS(__dllonexit)

#undef CRT_ALIAS
