/*
 * proxy.c -- LOGGING PROXY d3d8.dll for the STOCK game under Wine.
 *
 * The question this answers: does the ORIGINAL engine hand D3D8 the same
 * light/material values the port logs on its side? The only d3d8 import in
 * the game is Direct3DCreate8 (libIGGfx.dll), so exporting that one function
 * and wrapping the two COM objects it hands back intercepts every
 * IDirect3DDevice8 call the game will ever make.
 *
 * It also answers a second question the port could not settle on its own:
 * what CAPABILITY BLOCK the engine really sees. src/d3d8/d3d8_caps.c is a
 * declared profile, the engine branches on it once and for the whole run, and
 * its header says the Wine oracle is what settles it -- so GetDeviceCaps is
 * logged here in the same words the port logs its own, and the two diff.
 *
 * Everything else is forwarded untouched: exports other than Direct3DCreate8
 * are .def forwarders to d3d8_real.dll (built by build_stocklog.sh via
 * tools/pe.py proxydef), and vtable slots other than the logged ones are the
 * generic assembly trampolines in fwd.S, which swap `this` for the real
 * object and jmp to the real vtable slot (arg-count-agnostic because stdcall
 * is callee-cleanup).
 *
 * Slot numbers come from src/d3d8/d3d8_abi.h (triply verified -- see its
 * header): IDirect3D8: GetDeviceCaps = 13, CreateDevice = 15, 16 slots;
 * IDirect3DDevice8: GetDeviceCaps = 7, SetMaterial = 42, SetLight = 44,
 * LightEnable = 46, SetRenderState = 50, 97 slots (0..96).
 *
 * DELIBERATE LEAK: wrapper structs and their copied vtables are never
 * freed. Release is forwarded generically, so the real objects are released
 * correctly; only the few-hundred-byte wrappers leak. A run creates ONE
 * device, and mirroring the game's refcounting to free at the right moment
 * is complexity a diagnostic does not need.
 */
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

#define D3D8_SLOTS 16          /* IDirect3D8:        slots 0..15 */
#define D3DDEV_SLOTS 97        /* IDirect3DDevice8:  slots 0..96 */

#define SLOT_CREATE_DEVICE 15
#define SLOT_D3D8_GET_DEVICE_CAPS 13   /* IDirect3D8::GetDeviceCaps    */
#define SLOT_DEV_GET_DEVICE_CAPS 7     /* IDirect3DDevice8::GetDeviceCaps */
#define SLOT_SET_MATERIAL 42
#define SLOT_SET_LIGHT 44
#define SLOT_LIGHT_ENABLE 46
#define SLOT_SET_RENDER_STATE 50

#define D3DRS_LIGHTING 137
#define D3DRS_AMBIENT 139

/* Generated by fwd.S: one `swap-this-and-jmp` trampoline per slot. */
extern const void *fwd8_table[D3D8_SLOTS];
extern const void *fwddev_table[D3DDEV_SLOTS];

/* The wrapper IS the COM object the game sees: vtbl pointer first. */
struct wrap {
    const void **vtbl;       /* +0: our vtable (forwarders + logged slots) */
    void *real;              /* +4: the real COM object                    */
    const void **real_vtbl;  /* +8: real object's vtable (fwd.S reads this) */
};

/* Layouts from the D3D8 SDK; sizes are load-bearing (the game built these). */
typedef struct {                        /* 104 bytes, 26 dwords */
    DWORD Type;
    float Diffuse[4], Specular[4], Ambient[4];
    float Position[3], Direction[3];
    float Range, Falloff;
    float Attenuation0, Attenuation1, Attenuation2;
    float Theta, Phi;
} D3DLIGHT8;

typedef struct {
    float Diffuse[4], Ambient[4], Specular[4], Emissive[4];
    float Power;
} D3DMATERIAL8;

/*
 * D3DCAPS8, 53 four-byte fields. The field NAMES and their order come from
 * src/d3d8/d3d8_caps_fields.h -- the same list the port dumps its own block
 * from -- so the two logs are diffable line for line. Declaring the struct
 * from that list as well means a field added on one side cannot silently
 * shift the other.
 */
#include "../../src/d3d8/d3d8_caps_fields.h"

typedef struct {
#define F(name) DWORD name;
#define G(name) float name;
    D3D8_CAPS_FIELDS
#undef F
#undef G
} D3DCAPS8;

/* ------------------------------------------------------------------ log */

static FILE *g_log;
static HINSTANCE g_self;
static HMODULE g_realdll;
static char g_realpath[MAX_PATH] = "";

static void log_open(void) {
    if (g_log) return;
    /* Relative on purpose: run_shim cd's into the rundir, so the log lands
       in scratch/run/stocklog/. */
    g_log = fopen("d3d8_lightlog.txt", "a");
    if (g_log) setvbuf(g_log, NULL, _IOLBF, 4096);  /* a crash keeps the tail */
}

/* Named plog, not logf: <math.h>'s logf is a GCC builtin and shadowing it is a
   warning at every call site. printf-checked so a %f/%lu mismatch in a
   diagnostic is a compile error rather than a garbage number in the log. */
static void plog(const char *fmt, ...) __attribute__((format(printf, 1, 2)));
static void plog(const char *fmt, ...) {
    va_list ap;
    if (!g_log) return;
    va_start(ap, fmt);
    vfprintf(g_log, fmt, ap);
    va_end(ap);
    fputc('\n', g_log);
}

/* -------------------------------------------------- real d3d8 resolution */

/* Resolve WITHOUT loading (DllMain runs under loader lock; LoadLibrary of
   the real DXVK d3d8 happens later, at Direct3DCreate8). The string is
   recorded in the PROXY LOADED line so a fallback path is visible, not
   silently taken. Order: alongside the proxy (the rundir ships d3d8_real.dll),
   then syswow64, then whatever GetSystemDirectory says. */
static const char *find_real_path(void) {
    static char cand[MAX_PATH];
    char dir[MAX_PATH];
    DWORD n = GetModuleFileNameA(g_self, dir, MAX_PATH);
    if (n && n < MAX_PATH) {
        char *slash = strrchr(dir, '\\');
        if (slash) {
            *slash = 0;
            _snprintf(cand, MAX_PATH, "%s\\d3d8_real.dll", dir);
            if (GetFileAttributesA(cand) != INVALID_FILE_ATTRIBUTES)
                return cand;
        }
    }
    if (GetWindowsDirectoryA(dir, MAX_PATH)) {
        _snprintf(cand, MAX_PATH, "%s\\syswow64\\d3d8.dll", dir);
        if (GetFileAttributesA(cand) != INVALID_FILE_ATTRIBUTES)
            return cand;
    }
    if (GetSystemDirectoryA(dir, MAX_PATH)) {
        _snprintf(cand, MAX_PATH, "%s\\d3d8.dll", dir);
        if (GetFileAttributesA(cand) != INVALID_FILE_ATTRIBUTES)
            return cand;
    }
    return NULL;
}

typedef void *(WINAPI *Direct3DCreate8_t)(UINT);

static Direct3DCreate8_t get_real_create8(void) {
    if (g_realdll)
        return (Direct3DCreate8_t)(void *)GetProcAddress(g_realdll, "Direct3DCreate8");
    const char *path = find_real_path();
    if (path) {
        _snprintf(g_realpath, MAX_PATH, "%s", path);
        g_realdll = LoadLibraryA(path);
    }
    if (!g_realdll) {
        /* A silent NULL here looks EXACTLY like a game that renders nothing;
           say it loudly. */
        plog("PROXY ERROR t=%lu could not load the real d3d8.dll "
             "(tried alongside-proxy, syswow64, system dir) -- "
             "Direct3DCreate8 will return NULL", (unsigned long)GetTickCount());
        return NULL;
    }
    Direct3DCreate8_t p =
        (Direct3DCreate8_t)(void *)GetProcAddress(g_realdll, "Direct3DCreate8");
    if (!p)
        plog("PROXY ERROR t=%lu real d3d8 at %s has NO Direct3DCreate8 "
             "export -- Direct3DCreate8 will return NULL",
             (unsigned long)GetTickCount(), g_realpath);
    return p;
}

/* -------------------------------------------------------------- wrappers */

static void *wrap_alloc(void *real, const void **fwd_table, int nslots,
                        const char *what) {
    struct wrap *w = (struct wrap *)malloc(sizeof(struct wrap));
    const void **vt = (const void **)malloc(nslots * sizeof(void *));
    if (!w || !vt) {
        /* Passing the real object through unwrapped keeps the game alive but
           loses the log -- that must not be silent. */
        plog("PROXY ERROR t=%lu out of memory wrapping %s -- passing the "
             "REAL object through UNWRAPPED (no light logging from it)",
             (unsigned long)GetTickCount(), what);
        free(w); free(vt);
        return real;
    }
    memcpy(vt, fwd_table, nslots * sizeof(void *));
    w->vtbl = vt;
    w->real = real;
    w->real_vtbl = *(const void ***)real;
    return w;
}

/*
 * The REAL driver's capability block.
 *
 * src/d3d8/d3d8_caps.c is a DECLARED PROFILE and its header names what would
 * settle it: the stock game under Wine. This is that. Every field the port
 * promises and this machine does not is one `diff` line, and the engine
 * branches on these once and for the whole run -- so a difference here is a
 * DIFFERENT RENDERING PATH, not a cosmetic one.
 *
 * A failed call is logged with its HRESULT rather than skipped: an absent
 * CAPS block must not read as a block that matched.
 */
static void caps_dump(const D3DCAPS8 *c, const char *who) {
#define F(name) plog("CAPS %-28s = 0x%08lx", #name, (unsigned long)c->name);
#define G(name) plog("CAPS %-28s = %.6f", #name, (double)c->name);
    plog("CAPS BLOCK from %s -- %d field(s); compare with the port's",
         who, D3D8_CAPS_FIELD_COUNT);
    D3D8_CAPS_FIELDS
#undef F
#undef G
}

/* IDirect3D8::GetDeviceCaps (slot 13): (this, Adapter, DeviceType, pCaps) */
static HRESULT WINAPI d3d_GetDeviceCaps(struct wrap *w, UINT adapter,
                                        UINT devtype, D3DCAPS8 *caps) {
    typedef HRESULT (WINAPI *fn_t)(void *, UINT, UINT, D3DCAPS8 *);
    static int told;
    HRESULT hr = ((fn_t)w->real_vtbl[SLOT_D3D8_GET_DEVICE_CAPS])
        (w->real, adapter, devtype, caps);
    if (FAILED(hr) || !caps)
        plog("CAPS BLOCK from IDirect3D8::GetDeviceCaps(adapter=%u type=%u) "
             "UNAVAILABLE -- hr=0x%08lx caps=%p", (unsigned)adapter,
             (unsigned)devtype, (unsigned long)hr, (void *)caps);
    else if (!told++)
        caps_dump(caps, "IDirect3D8::GetDeviceCaps");
    return hr;
}

/* IDirect3DDevice8::GetDeviceCaps (slot 7): (this, pCaps) */
static HRESULT WINAPI dev_GetDeviceCaps(struct wrap *w, D3DCAPS8 *caps) {
    typedef HRESULT (WINAPI *fn_t)(void *, D3DCAPS8 *);
    static int told;
    HRESULT hr = ((fn_t)w->real_vtbl[SLOT_DEV_GET_DEVICE_CAPS])(w->real, caps);
    if (FAILED(hr) || !caps)
        plog("CAPS BLOCK from IDirect3DDevice8::GetDeviceCaps UNAVAILABLE -- "
             "hr=0x%08lx caps=%p", (unsigned long)hr, (void *)caps);
    else if (!told++)
        caps_dump(caps, "IDirect3DDevice8::GetDeviceCaps");
    return hr;
}

/* IDirect3DDevice8::SetMaterial (slot 42): (this, const D3DMATERIAL8*) */
static HRESULT WINAPI dev_SetMaterial(struct wrap *w, const D3DMATERIAL8 *m) {
    typedef HRESULT (WINAPI *fn_t)(void *, const D3DMATERIAL8 *);
    if (!m)
        plog("SETMATERIAL t=%lu NULL-POINTER", (unsigned long)GetTickCount());
    else
        plog("SETMATERIAL t=%lu diffuse=%.4f,%.4f,%.4f,%.4f "
             "ambient=%.4f,%.4f,%.4f,%.4f emissive=%.4f,%.4f,%.4f,%.4f "
             "specular=%.4f,%.4f,%.4f,%.4f power=%.2f",
             (unsigned long)GetTickCount(),
             m->Diffuse[0], m->Diffuse[1], m->Diffuse[2], m->Diffuse[3],
             m->Ambient[0], m->Ambient[1], m->Ambient[2], m->Ambient[3],
             m->Emissive[0], m->Emissive[1], m->Emissive[2], m->Emissive[3],
             m->Specular[0], m->Specular[1], m->Specular[2], m->Specular[3],
             m->Power);
    return ((fn_t)w->real_vtbl[SLOT_SET_MATERIAL])(w->real, m);
}

/* IDirect3DDevice8::SetLight (slot 44): (this, DWORD index, const D3DLIGHT8*) */
static HRESULT WINAPI dev_SetLight(struct wrap *w, DWORD idx,
                                   const D3DLIGHT8 *L) {
    typedef HRESULT (WINAPI *fn_t)(void *, DWORD, const D3DLIGHT8 *);
    if (!L)
        plog("SETLIGHT t=%lu idx=%lu NULL-POINTER",
             (unsigned long)GetTickCount(), (unsigned long)idx);
    else
        plog("SETLIGHT t=%lu idx=%lu type=%u "
             "diffuse=%.4f,%.4f,%.4f,%.4f specular=%.4f,%.4f,%.4f,%.4f "
             "ambient=%.4f,%.4f,%.4f,%.4f pos=%.2f,%.2f,%.2f "
             "dir=%.3f,%.3f,%.3f range=%.2f falloff=%.2f "
             "atten=%.6f,%.6f,%.8f theta=%.3f phi=%.3f",
             (unsigned long)GetTickCount(), (unsigned long)idx,
             (unsigned)L->Type,
             L->Diffuse[0], L->Diffuse[1], L->Diffuse[2], L->Diffuse[3],
             L->Specular[0], L->Specular[1], L->Specular[2], L->Specular[3],
             L->Ambient[0], L->Ambient[1], L->Ambient[2], L->Ambient[3],
             L->Position[0], L->Position[1], L->Position[2],
             L->Direction[0], L->Direction[1], L->Direction[2],
             L->Range, L->Falloff,
             L->Attenuation0, L->Attenuation1, L->Attenuation2,
             L->Theta, L->Phi);
    return ((fn_t)w->real_vtbl[SLOT_SET_LIGHT])(w->real, idx, L);
}

/* IDirect3DDevice8::LightEnable (slot 46): (this, DWORD index, BOOL on) */
static HRESULT WINAPI dev_LightEnable(struct wrap *w, DWORD idx, BOOL on) {
    typedef HRESULT (WINAPI *fn_t)(void *, DWORD, BOOL);
    plog("LIGHTENABLE t=%lu idx=%lu on=%d",
         (unsigned long)GetTickCount(), (unsigned long)idx, (int)on);
    return ((fn_t)w->real_vtbl[SLOT_LIGHT_ENABLE])(w->real, idx, on);
}

/* IDirect3DDevice8::SetRenderState (slot 50): (this, DWORD state, DWORD val).
   Only LIGHTING and AMBIENT are logged -- Present-rate calls would flood. */
static HRESULT WINAPI dev_SetRenderState(struct wrap *w, DWORD state,
                                         DWORD value) {
    typedef HRESULT (WINAPI *fn_t)(void *, DWORD, DWORD);
    if (state == D3DRS_LIGHTING)
        plog("SETRENDERSTATE t=%lu LIGHTING=%lu",
             (unsigned long)GetTickCount(), (unsigned long)value);
    else if (state == D3DRS_AMBIENT)
        plog("SETRENDERSTATE t=%lu AMBIENT=%08lx",
             (unsigned long)GetTickCount(), (unsigned long)value);
    return ((fn_t)w->real_vtbl[SLOT_SET_RENDER_STATE])(w->real, state, value);
}

static void *wrap_device(void *real) {
    void *p = wrap_alloc(real, fwddev_table, D3DDEV_SLOTS, "IDirect3DDevice8");
    if (p == real) return p;
    struct wrap *w = (struct wrap *)p;
    w->vtbl[SLOT_DEV_GET_DEVICE_CAPS] = (const void *)dev_GetDeviceCaps;
    w->vtbl[SLOT_SET_MATERIAL] = (const void *)dev_SetMaterial;
    w->vtbl[SLOT_SET_LIGHT] = (const void *)dev_SetLight;
    w->vtbl[SLOT_LIGHT_ENABLE] = (const void *)dev_LightEnable;
    w->vtbl[SLOT_SET_RENDER_STATE] = (const void *)dev_SetRenderState;
    return w;
}

/* IDirect3D8::CreateDevice (slot 15):
   (this, Adapter, DeviceType, hFocusWindow, BehaviorFlags,
    pPresentationParameters, ppReturnedDeviceInterface) */
static HRESULT WINAPI d3d_CreateDevice(struct wrap *w, UINT adapter,
                                       UINT devtype, HWND hwnd, DWORD flags,
                                       void *pparams, void **out) {
    typedef HRESULT (WINAPI *fn_t)(void *, UINT, UINT, HWND, DWORD, void *,
                                   void **);
    HRESULT hr = ((fn_t)w->real_vtbl[SLOT_CREATE_DEVICE])
        (w->real, adapter, devtype, hwnd, flags, pparams, out);
    plog("CREATEDEVICE t=%lu adapter=%u type=%u ok=%p",
         (unsigned long)GetTickCount(), (unsigned)adapter, (unsigned)devtype,
         (FAILED(hr) || !out) ? NULL : *out);
    if (SUCCEEDED(hr) && out && *out)
        *out = wrap_device(*out);
    return hr;
}

static void *wrap_d3d8(void *real) {
    void *p = wrap_alloc(real, fwd8_table, D3D8_SLOTS, "IDirect3D8");
    if (p == real) return p;
    struct wrap *w = (struct wrap *)p;
    w->vtbl[SLOT_CREATE_DEVICE] = (const void *)d3d_CreateDevice;
    w->vtbl[SLOT_D3D8_GET_DEVICE_CAPS] = (const void *)d3d_GetDeviceCaps;
    return w;
}

/* ------------------------------------------------------------ the export */

/* The ONE function the game imports from d3d8.dll. Exported via the .def
   (build_stocklog.sh regenerates it from the real DLL, forwarding the rest
   to d3d8_real). */
void *WINAPI Direct3DCreate8(UINT sdkver) {
    log_open();
    Direct3DCreate8_t real = get_real_create8();
    if (!real) {
        plog("DIRECT3DCREATE8 t=%lu sdk=%u ok=%p REAL-DLL-UNAVAILABLE",
             (unsigned long)GetTickCount(), (unsigned)sdkver, (void *)0);
        return NULL;
    }
    void *d3d = real(sdkver);
    plog("DIRECT3DCREATE8 t=%lu sdk=%u ok=%p",
         (unsigned long)GetTickCount(), (unsigned)sdkver, d3d);
    if (d3d)
        d3d = wrap_d3d8(d3d);
    return d3d;
}

BOOL WINAPI DllMain(HINSTANCE hinst, DWORD reason, void *reserved) {
    (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        g_self = hinst;
        log_open();
        const char *path = find_real_path();
        plog("PROXY LOADED t=%lu real_d3d8=%s",
             (unsigned long)GetTickCount(), path ? path : "NOT-FOUND-YET");
    }
    return TRUE;
}
