/**
 * YOUR_GAME_NAME - Recompiled Game Entry Point
 *
 * This is the Windows executable that hosts the recompiled game code.
 * It performs the following initialization sequence:
 *
 * 1. Load the original XBE file from disk
 * 2. Initialize the Xbox memory layout (map data sections to original VAs)
 * 3. Initialize the Xbox kernel replacement layer
 * 4. Initialize the kernel bridge (thunk table in Xbox memory)
 * 5. Set up game file paths for I/O redirection
 * 6. Initialize the stack pointer
 * 7. Install VEH crash handler for diagnostics
 * 8. Call the game's original entry point (recompiled)
 *
 * Customize this file for your game:
 *   - Set YOUR_GAME_ENTRY_POINT to the XBE entry point address
 *   - Set YOUR_GAME_XBE_PATH to where the XBE file lives
 *   - Set YOUR_GAME_DIR to the game data directory
 *   - Add any CRT global pre-initialization your game needs
 *   - Customize the VEH handler for game-specific crash diagnosis
 *
 * XBE Details (fill in from xbe_parser output):
 *   Title:       YOUR_GAME_NAME
 *   Title ID:    0x00000000
 *   Base addr:   0x00010000
 *   Entry point: 0x00000000
 *   Code size:   ~??? KB (.text)
 *   Sections:    ?? (list them)
 *   Kernel imports: ??
 */

/* dladdr (used by the crash handler to name the faulting recompiled
   function) is a GNU extension, so this must precede every include. */
#ifndef _WIN32
#define _GNU_SOURCE
#endif

#ifdef _WIN32
#include <windows.h>
#else
#include "win32_compat.h"   /* the toolkit's Win32 vocabulary for Linux builds */
#endif
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <dlfcn.h>   /* dladdr: name the recompiled function that faulted */

/* xboxrecomp runtime headers */
#include <xbox/xboxrecomp.h>

/*
 * If xboxrecomp.h is not an umbrella header in your setup, include
 * the individual headers directly:
 *
 * #include "kernel.h"
 * #include "xbox_memory_layout.h"
 * #include "d3d8_xbox.h"
 * #include "dsound_xbox.h"
 * #include "xinput_xbox.h"
 */

/* ── Global register state (defined in xbox_memory_layout.c) ── */

extern uint32_t g_eax, g_ecx, g_edx, g_esp;
extern uint32_t g_ebx, g_esi, g_edi;
extern uint32_t g_seh_ebp;
extern ptrdiff_t g_xbox_mem_offset;

/* ── XBE Constants ─────────────────────────────────────────── */

/*
 * TODO: Set these from your xbe_parser output.
 * Run: py -3 -m tools.xbe_parser game/default.xbe
 */
#define YOUR_GAME_ENTRY_POINT   0x00225A09  /* XBE entry point VA, from tools.xbe_parser */
/* Forward slashes: this build runs on Linux too, where a backslash is a
   legal filename character rather than a separator. */
#define YOUR_GAME_XBE_PATH      "game/default.xbe"
#define YOUR_GAME_DIR            "game"

/* ── Forward declarations ──────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size);

/* Recompiled entry point (generated by recomp pipeline) */
extern void xbe_entry_point(void);

/* NV2A GPU emulation (xbox_nv2a) -- see the VEH handler below */
#include "nv2a_mmio_hook.h"

/* ICALL miss accounting (recomp_manual.c) */
extern void recomp_icall_report(void);
extern void nh_report(void);   /* native CRT heap tally */
extern void recomp_stub_report(void);   /* empty-stub tally (generated) */
extern void recomp_abicheck_report(void);   /* callee-saved contract tally */
extern void recomp_esp_report(void);        /* simulated-stack bounds tally */
extern void recomp_icall_watch_init(void);   /* XBOX_ICALL_WATCH argument/return trace */
extern void recomp_icall_watch_report(void);
extern void listscan_report(void);   /* list-remove tail-shift observer */
extern void listfind_report(void); /* list find-by-name observer */
extern void listremove_report(void); /* --wrap isolation self-test */
extern void recomp_icall_watch_selftest(void);
extern void recomp_icall_selftest(void);

/* ── VEH crash handler ─────────────────────────────────────── */

/*
 * Vectored Exception Handler for crash diagnostics.
 *
 * When the recompiled game hits an access violation, this handler prints
 * the faulting address, all Xbox register values, and a native stack trace.
 * This is your primary debugging tool during bring-up.
 *
 * Customize this for your game:
 *   - Add game-specific address checks (GPU register probes, etc.)
 *   - Add dumps of game-specific globals (heap handles, state flags)
 *   - Add SEH simulation if your game uses __try/__except
 */
static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
        uintptr_t fault_addr = ep->ExceptionRecord->ExceptionInformation[1];

        /*
         * NV2A GPU register access at 0xFD000000-0xFDFFFFFF.
         *
         * This is not a crash: it is how the game draws. The Xbox D3D8
         * library compiled into this XBE writes GPU registers and a push
         * buffer directly, so the recompiled code faults on every one of
         * them. The toolkit's xbox_nv2a library (xemu's NV2A emulation)
         * decodes the faulting instruction, performs the register access,
         * and advances RIP -- and its PGRAPH translator turns the resulting
         * push-buffer methods into calls on the toolkit's IDirect3DDevice8,
         * which on Linux is backed by OpenGL.
         *
         * Passing these faults through, as this handler used to, means the
         * GPU never sees a single command.
         *
         * A fault we cannot decode is reported rather than skipped: silently
         * resuming past an undecoded GPU write drops a draw command and
         * leaves a black screen with nothing in the log to explain it.
         */
        if (fault_addr >= (uintptr_t)g_xbox_mem_offset + 0xFD000000 &&
            fault_addr <  (uintptr_t)g_xbox_mem_offset + 0xFE000000) {
            uint32_t va = (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset);
            int is_write = (int)ep->ExceptionRecord->ExceptionInformation[0];
            static unsigned long undecoded;

            if (nv2a_hook_handle_mmio(ep->ContextRecord, fault_addr, va, is_write))
                return EXCEPTION_CONTINUE_EXECUTION;

            if (undecoded++ < 16) {
                fprintf(stderr, "[NV2A] could NOT decode the %s at RIP=0x%llX "
                                "touching GPU register 0x%08X -- this access is "
                                "lost, not deferred\n",
                        is_write ? "write" : "read",
                        (unsigned long long)ep->ContextRecord->Rip, va);
                fflush(stderr);
            }
            return EXCEPTION_CONTINUE_SEARCH;
        }

        /* GPU framebuffer / push buffer window. */
        if (fault_addr >= (uintptr_t)g_xbox_mem_offset + 0xF0000000 &&
            fault_addr <  (uintptr_t)g_xbox_mem_offset + 0xFD000000) {
            uint32_t va = (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset);
            if (nv2a_hook_handle_vram(fault_addr, va))
                return EXCEPTION_CONTINUE_EXECUTION;
        }

        /* Print the run totals here too. A crash used to skip the end-of-run
           report entirely, so a run that died could not be compared against
           one that finished -- the two looked like different experiments. */
        recomp_icall_report();
        nh_report();
        recomp_stub_report();
        recomp_abicheck_report();
        recomp_esp_report();
        recomp_icall_watch_report();
        listscan_report();
        listfind_report();
        listremove_report();

        fprintf(stderr, "[CRASH] Access violation at RIP=0x%llX, fault addr=0x%llX (%s)\n",
            (unsigned long long)ep->ContextRecord->Rip,
            (unsigned long long)fault_addr,
            ep->ExceptionRecord->ExceptionInformation[0] ? "write" : "read");
        fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        fprintf(stderr, "  Xbox VA of fault: 0x%08X\n",
            (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset));

        /*
         * TODO: Add game-specific diagnostics here. Examples:
         *
         * Dump CRT heap handle:
         *   uint32_t heap = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + HEAP_HANDLE_VA);
         *   fprintf(stderr, "  CRT heap handle: 0x%08X\n", heap);
         *
         * Dump game state:
         *   uint32_t state = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + GAME_STATE_VA);
         *   fprintf(stderr, "  Game state: %u\n", state);
         */

        /*
         * Name the recompiled function that faulted, and the ones that called
         * it.
         *
         * This used to filter the stack for 0x140000000..0x150000000, the
         * default image base of a Windows PE. Nothing on Linux is ever mapped
         * there (this binary lands around 0x55...), so the loop matched
         * nothing and the report printed a header with no rows under it --
         * indistinguishable from "the stack was empty", and read for several
         * runs as if there were simply nothing to show.
         *
         * dladdr resolves a return address to the nearest exported symbol,
         * which for generated code is the sub_XXXXXXXX whose name carries the
         * original Xbox VA. That is the thing worth knowing; an unresolved hex
         * address is not. Needs -rdynamic so the symbols are in .dynsym.
         */
        {
            uintptr_t *sp = (uintptr_t *)ep->ContextRecord->Rsp;
            Dl_info info;
            int shown = 0, scanned = 0;

            if (dladdr((void *)(uintptr_t)ep->ContextRecord->Rip, &info) &&
                info.dli_sname) {
                fprintf(stderr, "  Faulting function: %s (+0x%lX)\n",
                        info.dli_sname,
                        (unsigned long)((uintptr_t)ep->ContextRecord->Rip -
                                        (uintptr_t)info.dli_saddr));
            } else {
                fprintf(stderr, "  Faulting function: UNRESOLVED at RIP=0x%llX"
                        " (build without -rdynamic?)\n",
                        (unsigned long long)ep->ContextRecord->Rip);
            }

            fprintf(stderr, "  Native call stack (nearest symbol per return address):\n");
            for (int i = 0; i < 256; i++, scanned++) {
                if (!sp[i]) continue;
                if (dladdr((void *)sp[i], &info) && info.dli_sname) {
                    /* Only code addresses resolve to a function symbol; stack
                       garbage that happens to be a valid pointer resolves to
                       a data symbol or not at all. */
                    fprintf(stderr, "    [%d] %s +0x%lX\n", i, info.dli_sname,
                            (unsigned long)(sp[i] - (uintptr_t)info.dli_saddr));
                    if (++shown >= 24) break;
                }
            }
            /* A negative result states its denominator, so "no frames" cannot
               be confused with "never looked". */
            fprintf(stderr, "    %d frame(s) resolved from %d stack slots scanned\n",
                    shown, scanned);
        }
        fflush(stderr);
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

/* ── WinMain ───────────────────────────────────────────────── */

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine, int nCmdShow)
{
    void *xbe_data = NULL;
    size_t xbe_size = 0;

    (void)hInstance;
    (void)hPrevInstance;
    (void)lpCmdLine;
    (void)nCmdShow;

    /* Unbuffered output for immediate visibility during debugging */
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);

    printf("=== X-Men Legends II (Xbox) - Static Recompilation ===\n");
    printf("Loading XBE...\n");

    /* Install VEH handler (first handler in chain) */
    AddVectoredExceptionHandler(1, veh_handler);

    /* Prove the ICALL miss instrument fires before trusting its silence. */
    {
        const char *st = getenv("XBOX_ICALL_SELFTEST");
        if (st && st[0] == '1')
            recomp_icall_selftest();
    }

    /* Step 1: Load XBE */
    if (!load_xbe(YOUR_GAME_XBE_PATH, &xbe_data, &xbe_size)) {
        MessageBoxA(NULL, "Failed to load default.xbe.\n"
                    "Place the game files in the 'game' subdirectory.",
                    "Recomp", MB_ICONERROR);
        return 1;
    }
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* Step 2: Initialize Xbox memory layout */
    printf("Initializing Xbox memory layout...\n");
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        MessageBoxA(NULL, "Failed to initialize Xbox memory layout.\n"
                    "The required virtual address range may be unavailable.",
                    "Recomp", MB_ICONERROR);
        free(xbe_data);
        return 1;
    }

    g_xbox_mem_offset = xbox_GetMemoryOffset();

    /* The watch reads its arguments out of guest memory, so it can only be
       armed once that memory exists -- and it must be armed before any game
       code runs, or a target called during startup is missed and then
       reported as NEVER CALLED. Here is the only point that is both. */
    {
        const char *ws = getenv("XBOX_ICALL_WATCH_SELFTEST");
        if (ws && ws[0] == '1')
            recomp_icall_watch_selftest();
    }
    recomp_icall_watch_init();
    printf("Xbox memory mapped. Offset: 0x%llX\n", (unsigned long long)g_xbox_mem_offset);

    /* Step 3: Initialize Xbox kernel */
    printf("Initializing Xbox kernel replacement...\n");
    xbox_kernel_init();

    /* Step 3b: Initialize the NV2A GPU. Must precede any game code: the
       first D3D call writes GPU registers, and without this the VEH has
       nothing to hand those writes to. */
    printf("Initializing NV2A GPU emulation...\n");
    nv2a_hook_init(g_xbox_mem_offset);

    /* Step 4: Set game directory for file I/O path translation */
    {
        extern void xbox_path_init(const char *game_dir, const char *save_dir);
        xbox_path_init(YOUR_GAME_DIR, NULL);
    }

    /* Step 5: Initialize kernel bridge (thunk table in Xbox memory) */
    printf("Initializing kernel bridge...\n");
    xbox_kernel_bridge_init();

    /* Step 6: Initialize stack */
    g_esp = XBOX_STACK_TOP;

    /*
     * TODO: Pre-initialize CRT globals if needed.
     *
     * Many Xbox games use the MSVC CRT. The CRT's __heap_init sets up a
     * heap descriptor at a game-specific address. You may need to
     * pre-initialize __active_heap to avoid small-block heap issues:
     *
     *   uint32_t *active_heap = (uint32_t *)((uint8_t *)g_xbox_mem_offset + ACTIVE_HEAP_VA);
     *   *active_heap = 1;  // 1 = system heap (HeapAlloc), avoids SBH init
     *
     * Find ACTIVE_HEAP_VA by searching the disassembly for __heap_init
     * or by looking for the CRT's __active_heap global in the data section.
     */

    printf("\n=== Initialization complete ===\n");
    printf("Entry point: 0x%08X\n", YOUR_GAME_ENTRY_POINT);
    printf("ESP: 0x%08X\n", g_esp);

    /* Step 7: Call the recompiled entry point */
    printf("\nStarting game...\n");
    fflush(stdout);

    xbe_entry_point();

    printf("\nGame returned. Cleaning up...\n");

    /* An indirect call that could not be resolved is skipped silently by the
       ICALL macros, so "the game returned" says nothing about whether it ran.
       Print the miss tally before anything else -- always, zero included. */
    recomp_icall_report();
    nh_report();
    recomp_stub_report();
    recomp_abicheck_report();
    recomp_esp_report();
    recomp_icall_watch_report();
    listscan_report();
    listfind_report();
    listremove_report();

    /* Cleanup */
    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);

    return 0;
}

/* ── XBE Loading ───────────────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        return FALSE;
    }

    void *data = malloc((size_t)size);
    if (!data) {
        fclose(f);
        return FALSE;
    }

    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }

    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}

/* Console entry point (for debugging -- lets you see printf output) */
int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return WinMain(GetModuleHandle(NULL), NULL, GetCommandLineA(), SW_SHOW);
}


