/* GENERATED by tools/device_slots.py -- do not edit.
 *
 * Regenerate with:
 *   python3 tools/device_slots.py scratch/recomp/libIGGfx.json \
 *       scratch/recomp/libIGGfx.vtab.json --class igDx8VisualContext \
 *       --header src/vulkan/igvk_device_slots.h
 *
 * The slots of igDx8VisualContext's vtable that reach the DirectX device fields
 * (this+0x140/0x144/0x148/0x14c), following DIRECT calls to depth 6.
 * Everything NOT listed here is platform-neutral engine bookkeeping and is
 * inherited verbatim (C119).
 *
 * 98 of 334 slots, 0 of which could not be scanned at
 * all (no translated instructions) and are therefore NOT in the list.
 *
 * LOWER BOUND, three ways: direct calls only, so a slot reaching the device
 * through a function pointer or a vtable dispatch is absent; the match is on
 * the offset constant, so an access off an already-advanced base is invisible;
 * and the unscanned functions above were never looked at. A slot missing from
 * this list is inherited, and an inherited device-touching slot calls through
 * a device this host never made.
 */
#define IGVK_DEVICE_SLOT_COUNT 98
static const short IGVK_DEVICE_SLOTS[IGVK_DEVICE_SLOT_COUNT] = {
       7,   8,  25,  30,  34,  35,  36,  38,  46,  47,  50,  72,
      73,  79,  82,  84,  86,  88,  90,  92,  94,  96, 100, 113,
     115, 117, 127, 128, 130, 133, 137, 139, 141, 143, 146, 147,
     151, 153, 155, 157, 159, 160, 162, 164, 166, 168, 170, 172,
     173, 174, 175, 177, 186, 196, 203, 204, 205, 206, 207, 208,
     210, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238,
     240, 242, 244, 246, 248, 250, 252, 254, 273, 275, 276, 281,
     283, 297, 302, 303, 308, 309, 314, 316, 321, 323, 328, 329,
     331, 333,
};
