#!/usr/bin/env python3
"""check_emitted — shared x86 translator toolchain, run from this port.

The tool lives in the `recomp-x86` repo: the x86-32 lifter serves this PC port
and an original-Xbox one alike (OG Xbox is x86), so it is not this port's to
own. It resolves the PORT from the working directory, which is why this shim
only has to find it and hand over.

The --selftest is LOCAL, and that is a recorded defect in the shared revision
this port pins (recomp-x86 5a241a6): its own `emitted_fingerprint` documents
that the override set and the routing file are NO LONGER inputs to emitted
code ("emitted code is identical whether or not a function is overridden"),
but the shared selftest still asserts the opposite and so fails against its
own implementation. The checks below assert the CURRENT contract, including
the two inverted: an override-set or routing change must NOT move the
fingerprint. If the shared tool ever makes them move again, that belongs in
this gate, because it would force every module to re-emit for a change that
cannot alter a byte of them.
"""
import os
import runpy
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from shared_dir import shared_dir

_shared = os.path.join(shared_dir("recomp-x86", "tools/check_emitted.py"),
                       "tools", "check_emitted.py")
_shared_globals = runpy.run_path(_shared)

fingerprint = _shared_globals["fingerprint"]
stamp_of = _shared_globals["stamp_of"]
RECOMP = _shared_globals["RECOMP"]
TOOL_ROOT = _shared_globals["TOOL_ROOT"]


def selftest():
    """The stamp gate must fire on stale and pass on current, and the
    fingerprint must be exactly the translator's bytes -- nothing else."""
    ok = True
    d = tempfile.mkdtemp(prefix="emitted-stamp-", dir=os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "scratch"))
    root = os.path.join(d, "port")
    os.makedirs(os.path.join(root, "src", "native"))
    with open(os.path.join(root, "src", "native", "base.c"), "w") as f:
        f.write('x86_register_override("Game.exe", 0x00401000, f);\n')

    good = os.path.join(d, "m_000.c")
    with open(good, "w") as f:
        f.write("/* generated */\n/* recomp-fingerprint: %s */\nint x;\n"
                % fingerprint(root=root, program="Game.exe"))
    if stamp_of(good) != fingerprint(root=root, program="Game.exe"):
        ok = False
        print("  FAIL  a current stamp was not read back")
    else:
        print("  pass  a current stamp is read back")

    bad = os.path.join(d, "n_000.c")
    with open(bad, "w") as f:
        f.write("/* generated */\n/* recomp-fingerprint: deadbeefdeadbeef */\n")
    if stamp_of(bad) == fingerprint(root=root, program="Game.exe"):
        ok = False
        print("  FAIL  a stale stamp read as current")
    else:
        print("  pass  a stale stamp is seen as stale (%s)" % stamp_of(bad))

    none = os.path.join(d, "o_000.c")
    with open(none, "w") as f:
        f.write("/* generated by something older */\nint y;\n")
    if stamp_of(none) is not None:
        ok = False
        print("  FAIL  an unstamped file read as stamped")
    else:
        print("  pass  an unstamped file reads as None, which counts as stale")

    with open(RECOMP, "rb") as f:
        translator = f.read()
    tweaked = os.path.join(d, "recomp_tweaked.py")
    with open(tweaked, "wb") as f:
        f.write(translator + b"\n# a translator change\n")
    if fingerprint(tweaked, root, "Game.exe") \
            == fingerprint(RECOMP, root, "Game.exe"):
        ok = False
        print("  FAIL  editing the translator did not change the fingerprint")
    else:
        print("  pass  editing the translator changes the fingerprint")

    # The v2 contract: the override set and the routing file are NOT inputs.
    # 5a241a6 removed them because emitted code is identical whether or not a
    # function is overridden; including them forced re-emission of every
    # module for a change that cannot alter a byte.
    before = fingerprint(root=root, program="Game.exe")
    with open(os.path.join(root, "src", "native", "more.c"), "w") as f:
        f.write('x86_register_override("Game.exe", 0x00402000, g);\n')
    if fingerprint(root=root, program="Game.exe") != before:
        ok = False
        print("  FAIL  an override-set addition changed the fingerprint "
              "(v2 contract violated: emitted code does not depend on it)")
    else:
        print("  pass  an override-set addition leaves the fingerprint alone "
              "(v2 contract: emitted code does not depend on it)")

    routing_tweaked = os.path.join(d, "overrides_tweaked.py")
    routing = os.path.join(TOOL_ROOT, "tools", "recomp_overrides.py")
    with open(routing, "rb") as f:
        body = f.read()
    with open(routing_tweaked, "wb") as f:
        f.write(body + b"\n# a routing change\n")
    emitted_fingerprint = _shared_globals["emitted_fingerprint"]
    if emitted_fingerprint(RECOMP, root, "Game.exe", routing) \
            != emitted_fingerprint(RECOMP, root, "Game.exe", routing_tweaked):
        ok = False
        print("  FAIL  editing override routing changed the fingerprint "
              "(v2 contract violated: it is no longer an input)")
    else:
        print("  pass  editing override routing leaves the fingerprint alone "
              "(v2 contract)")

    before = fingerprint(root=root, program="Game.exe")
    with open(os.path.join(root, "src", "native", "other.c"), "w") as f:
        f.write('x86_register_override("Other.dll", 0x10001000, h);\n')
    if fingerprint(root=root, program="Game.exe") != before:
        ok = False
        print("  FAIL  another module's override changed this fingerprint")
    else:
        print("  pass  another module's override leaves this fingerprint alone")

    import shutil
    shutil.rmtree(d)
    print("\nSELFTEST", "PASSED" if ok else "FAILED")
    return 0 if ok else 1


def main(argv):
    if "--selftest" in argv:
        return selftest()
    code = _shared_globals["main"](argv)
    # runpy already ran the shared module top level with __name__ != main, so
    # its __main__ guard did not fire; call its main directly.
    return code


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
