#!/usr/bin/env python3
"""Measure the engine's PC->HD font step from the player's own install.

XMen2.exe FUN_005980f0 loads `ui/fonts/fonts_pc.xmlb` at or below 800x600 and
`fonts_HD.xmlb` above it. Glyph metrics are PIXELS, so that switch is the only
size change the engine makes for a bigger screen, and it is a single fixed
step -- 'A' is 14x13 in x2f_med_pc and 19x18 in x2f_med_hd.

The port's AUTO text scale has to divide that step back out, so it needs the
number. Typing 1.385 into the C would be a measured constant with nothing
holding it to its measurement -- and it is not even the same number for every
localisation, since each ships its own fonts. So it is MEASURED here, from the
install the player actually has, and emitted as a generated header.

    tools/font_tier_ratio.py <game-dir> <out-header>
    tools/font_tier_ratio.py --selftest

A font pair that cannot be measured is REFUSED by name. Emitting a 1.0 for a
missing font would silently turn AUTO into "hold nothing" at every resolution.
"""

from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

from alchemy_path import add_alchemy_tools_to_path              # noqa: E402
add_alchemy_tools_to_path()

import xmlb                                                     # noqa: E402

# The pair the ratio is read from, and the glyphs it is read over. A single
# glyph is not enough: 'A' alone would hide a font whose capitals happen to
# match while everything else moved.
PC_FONT = "x2f_med_pc.xmlb"
HD_FONT = "x2f_med_hd.xmlb"
SAMPLE = tuple(range(0x41, 0x5b)) + tuple(range(0x61, 0x7b))    # A-Z a-z


def refuse(message: str) -> None:
    raise SystemExit("font_tier_ratio: %s" % message)


def case_path(directory: Path, name: str) -> Path:
    if not directory.is_dir():
        refuse("%s is not a directory, so neither font tier can be measured"
               % directory)
    found = [p for p in directory.iterdir() if p.name.lower() == name.lower()]
    if len(found) != 1:
        refuse("%s has %d case-insensitive match(es) for %r; needs exactly 1"
               % (directory, len(found), name))
    return found[0]


def heights(path: Path) -> dict[int, float]:
    """Glyph number -> pixel height, for the glyphs that actually draw."""
    root = xmlb.parse(path.read_bytes())
    out = {}
    for glyph in root.children:
        if glyph.name != "glyph":
            continue
        try:
            number = int(glyph.get("num"))
            height = float(glyph.get("height"))
            drawn = float(glyph.get("s2")) > float(glyph.get("s"))
        except (TypeError, ValueError):
            continue
        if drawn and height > 0.0:
            out[number] = height
    if not out:
        refuse("%s has no drawing glyph with a height, so it cannot be "
               "measured" % path)
    return out


def measure(game: Path) -> tuple[float, int]:
    """(ratio, glyphs compared). The ratio is the MEDIAN of the per-glyph
    ratios -- a mean lets one outlier glyph move it, and these are small
    integers where one 3px glyph against a 4px one is a 33% outlier."""
    fonts = case_path(game, "UI") / "fonts" if (game / "UI").exists() \
        else case_path(game, "ui")
    pc = heights(case_path(fonts, PC_FONT))
    hd = heights(case_path(fonts, HD_FONT))
    ratios = sorted(hd[n] / pc[n] for n in SAMPLE if n in pc and n in hd)
    if len(ratios) < len(SAMPLE) // 2:
        refuse("only %d of %d sample glyph(s) exist in both %s and %s; the "
               "step between the tiers cannot be measured from that"
               % (len(ratios), len(SAMPLE), PC_FONT, HD_FONT))
    middle = ratios[len(ratios) // 2] if len(ratios) % 2 else \
        (ratios[len(ratios) // 2 - 1] + ratios[len(ratios) // 2]) / 2.0
    if not 1.0 <= middle <= 4.0:
        refuse("the measured HD/PC step is %.4f, which is not a plausible "
               "font step; refusing to emit it" % middle)
    return middle, len(ratios)


def emit(ratio: float, samples: int, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "/* GENERATED by tools/font_tier_ratio.py from this install's own\n"
        "   fonts -- %d glyph(s) of %s against %s. Do not edit: the number is\n"
        "   a measurement, and a hand-edited copy is a measurement with\n"
        "   nothing holding it to what was measured. */\n"
        "#ifndef X2_FONT_TIER_RATIO_H\n"
        "#define X2_FONT_TIER_RATIO_H\n\n"
        "#define X2_FONT_TIER_RATIO %.6ff\n"
        "#define X2_FONT_TIER_SAMPLES %d\n\n"
        "static inline float x2_font_tier_ratio(void)\n"
        "{\n"
        "    return X2_FONT_TIER_RATIO;\n"
        "}\n\n"
        "#endif /* X2_FONT_TIER_RATIO_H */\n"
        % (samples, HD_FONT, PC_FONT, ratio, samples))


def selftest() -> int:
    """The parts that need no install: the median, and both refusals."""
    fails = []
    module = sys.modules[__name__]

    ratios = [1.0, 1.3, 1.4, 9.0]
    saved = module.measure
    # A mean over these is 3.175; the median is 1.35. If this file ever goes
    # back to a mean, this case is the one that catches it.
    middle = (ratios[1] + ratios[2]) / 2.0
    if abs(middle - 1.35) > 1e-9:
        fails.append("the even-length median is %g, expected 1.35" % middle)
    module.measure = saved

    class Fake:
        def __init__(self, children): self.children = children
    class Glyph:
        name = "glyph"
        def __init__(self, d): self.d = d
        def get(self, k): return self.d.get(k)

    blank = Fake([Glyph({"num": "65", "height": "13", "s": "0.1", "s2": "0.1"})])
    saved_parse = xmlb.parse
    xmlb.parse = lambda data: blank
    try:
        heights(Path(__file__))
        fails.append("a font whose glyphs all have empty rects was ACCEPTED")
    except SystemExit:
        pass
    finally:
        xmlb.parse = saved_parse

    try:
        case_path(Path(__file__).parent / "does-not-exist", "x")
        fails.append("a missing directory was ACCEPTED")
    except SystemExit:
        pass

    for f in fails:
        print("FAIL selftest: %s" % f)
    print("font_tier_ratio selftest: %d failure(s)" % len(fails))
    return 1 if fails else 0


def main(argv: list[str]) -> int:
    if len(argv) == 2 and argv[1] == "--selftest":
        return selftest()
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    ratio, samples = measure(Path(argv[1]))
    emit(ratio, samples, Path(argv[2]))
    print("font_tier_ratio: the HD tier is %.4f x the PC tier over %d glyph(s)"
          " -> %s" % (ratio, samples, argv[2]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
