#!/usr/bin/env python3
"""Generate both halves of the native-override wiring from src/native/overrides.json.

    tools/gen_overrides.py [--check]

An override needs two things that must agree, and the whole point of this file
is that they cannot disagree:

  1. the overridden function emitted into a translation unit of ITS OWN, so
     `ld --wrap` can intercept its call sites -- generated as
     scratch/recomp/<module>.isolate, consumed by `recomp.py emit --isolate`;

  2. the link flags `-Wl,--wrap=<symbol>` -- generated as
     src/recomp/gen/recomp_overrides.cmake, included by CMakeLists.txt.

Maintaining those by hand is how the Xbox side lost two RtlAllocateHeap call
sites and an entire observer: --wrap only redirects calls that CROSS an object
file, so an override sharing a chunk with its caller binds at compile time and
never fires. It links, it reports nothing, and every result taken from that run
is wrong in a way nothing announces.

`--check` exits non-zero if the generated files are missing or stale, which is
the pre-commit/CI form of the same guarantee.

WHAT A NEGATIVE PRINTS: with no overrides declared, this writes an EMPTY cmake
fragment that still defines RECOMP_OVERRIDE_WRAPS (so the build does not break)
and says so on stdout. It never silently writes nothing.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "native", "overrides.json")
CMAKE_OUT = os.path.join(ROOT, "src", "recomp", "gen", "recomp_overrides.cmake")
ISOLATE_DIR = os.path.join(ROOT, "scratch", "recomp")


def load():
    if not os.path.exists(SRC):
        sys.exit("gen_overrides: %s does not exist. It is the single source of "
                 "truth for native overrides; refusing to generate wiring from "
                 "nothing." % SRC)
    with open(SRC) as f:
        d = json.load(f)
    out = []
    for i, o in enumerate(d.get("overrides", [])):
        for k in ("module", "ep", "symbol"):
            if k not in o:
                sys.exit("gen_overrides: overrides[%d] has no %r" % (i, k))
        try:
            ep = int(o["ep"], 16)
        except ValueError:
            sys.exit("gen_overrides: overrides[%d] ep %r is not hex"
                     % (i, o["ep"]))
        out.append((o["module"], ep, o["symbol"]))
    return out


def render_cmake(ovr):
    lines = [
        "# GENERATED by tools/gen_overrides.py from src/native/overrides.json.",
        "# Do not edit: edit the json and re-run, or the --wrap flags and the",
        "# --isolate list drift apart and overrides silently stop firing.",
        "",
    ]
    if not ovr:
        lines += [
            "# No native overrides are declared.",
            "set(RECOMP_OVERRIDE_WRAPS \"\")",
            "",
        ]
    else:
        lines.append("set(RECOMP_OVERRIDE_WRAPS")
        for mod, ep, sym in ovr:
            lines.append("    -Wl,--wrap=%s        # %s 0x%08x" % (sym, mod, ep))
        lines += [")", ""]
    return "\n".join(lines) + "\n"


def main(argv):
    check = "--check" in argv
    ovr = load()

    by_mod = {}
    for mod, ep, sym in ovr:
        by_mod.setdefault(mod, []).append(ep)

    cmake = render_cmake(ovr)
    stale = []

    if check:
        cur = open(CMAKE_OUT).read() if os.path.exists(CMAKE_OUT) else None
        if cur != cmake:
            stale.append(CMAKE_OUT)
    else:
        os.makedirs(os.path.dirname(CMAKE_OUT), exist_ok=True)
        with open(CMAKE_OUT, "w") as f:
            f.write(cmake)

    for mod, eps in by_mod.items():
        path = os.path.join(ISOLATE_DIR, mod + ".isolate")
        body = "".join("0x%08x\n" % e for e in sorted(eps))
        if check:
            cur = open(path).read() if os.path.exists(path) else None
            if cur != body:
                stale.append(path)
        else:
            os.makedirs(ISOLATE_DIR, exist_ok=True)
            with open(path, "w") as f:
                f.write(body)

    if check:
        if stale:
            print("gen_overrides: STALE or missing: %s" % ", ".join(stale))
            print("  Run tools/gen_overrides.py and re-emit the affected "
                  "module(s), or the overrides will not fire.")
            return 1
        print("gen_overrides: generated wiring is up to date (%d override(s))"
              % len(ovr))
        return 0

    if not ovr:
        print("gen_overrides: NO overrides are declared. Wrote an empty "
              "%s so the build still defines RECOMP_OVERRIDE_WRAPS."
              % os.path.relpath(CMAKE_OUT, ROOT))
        return 0

    print("gen_overrides: %d override(s)" % len(ovr))
    for mod, ep, sym in ovr:
        print("    %-10s 0x%08x  %s" % (mod, ep, sym))
    print("  wrote %s" % os.path.relpath(CMAKE_OUT, ROOT))
    for mod in sorted(by_mod):
        print("  wrote %s  (%d ep) -- re-emit with: python3 tools/recomp.py "
              "emit scratch/recomp/%s.json src/recomp/%s.c --split 1500 "
              "--isolate scratch/recomp/%s.isolate"
              % (os.path.relpath(os.path.join(ISOLATE_DIR, mod + ".isolate"),
                                 ROOT), len(by_mod[mod]), mod, mod, mod))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
