#!/usr/bin/env python3
"""Generate both halves of the native-override wiring from src/native/overrides.json.

    tools/gen_overrides.py [--check]

An override needs two things that must agree, and the whole point of this file
is that they cannot disagree:

  1. the overridden function emitted into a translation unit of ITS OWN, so
     `ld --wrap` can intercept its call sites -- generated as
     scratch/recomp/<module>.isolate, consumed by `recomp.py emit --isolate`;

  2. the link flags `-Wl,--wrap=<symbol>` -- generated as
     src/recomp/gen/recomp_overrides.cmake, included by CMakeLists.txt.

Maintaining those by hand is how the Xbox side lost two RtlAllocateHeap call
sites and an entire observer: --wrap only redirects calls that CROSS an object
file, so an override sharing a chunk with its caller binds at compile time and
never fires. It links, it reports nothing, and every result taken from that run
is wrong in a way nothing announces.

`--check` exits non-zero if the generated files are missing or stale, which is
the pre-commit/CI form of the same guarantee.

WHAT A NEGATIVE PRINTS: with no overrides declared, this writes an EMPTY cmake
fragment that still defines RECOMP_OVERRIDE_WRAPS (so the build does not break)
and says so on stdout. It never silently writes nothing.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "native", "overrides.json")
CMAKE_OUT = os.path.join(ROOT, "src", "recomp", "gen", "recomp_overrides.cmake")
ISOLATE_DIR = os.path.join(ROOT, "scratch", "recomp")


def load():
    if not os.path.exists(SRC):
        sys.exit("gen_overrides: %s does not exist. It is the single source of "
                 "truth for native overrides; refusing to generate wiring from "
                 "nothing." % SRC)
    with open(SRC) as f:
        d = json.load(f)
    out = []
    for i, o in enumerate(d.get("overrides", [])):
        for k in ("module", "ep", "symbol"):
            if k not in o:
                sys.exit("gen_overrides: overrides[%d] has no %r" % (i, k))
        try:
            ep = int(o["ep"], 16)
        except ValueError:
            sys.exit("gen_overrides: overrides[%d] ep %r is not hex"
                     % (i, o["ep"]))
        rv = o.get("returns", "value")
        if rv not in ("value", "void"):
            sys.exit("gen_overrides: overrides[%d] returns %r; it is \"value\" "
                     "(the default) or \"void\", and \"void\" has to be "
                     "justified in `why` by the CALL SITES that were checked"
                     % (i, rv))
        out.append((o["module"], ep, o["symbol"], rv))
    return out


def render_cmake(ovr):
    lines = [
        "# GENERATED by tools/gen_overrides.py from src/native/overrides.json.",
        "# Do not edit: edit the json and re-run, or the --wrap flags and the",
        "# --isolate list drift apart and overrides silently stop firing.",
        "",
    ]
    if not ovr:
        lines += [
            "# No native overrides are declared.",
            "set(RECOMP_OVERRIDE_WRAPS \"\")",
            "",
        ]
    else:
        lines.append("set(RECOMP_OVERRIDE_WRAPS")
        for mod, ep, sym, rv in ovr:
            lines.append("    -Wl,--wrap=%s        # %s 0x%08x" % (sym, mod, ep))
        lines += [")", ""]
    return "\n".join(lines) + "\n"


# Every file that may hold a __wrap_ body. It is a DIRECTORY scan, not a
# filename: the check exists to catch an override declared with no
# implementation, and a hard-coded "overrides.c" reports exactly that failure
# for an override that is correctly implemented somewhere else -- which is what
# it did the moment the conversation port landed in its own file. A stale
# checker that cries wolf gets switched off, and then the real case goes by.
OVERRIDE_DIR = os.path.join(ROOT, "src", "native")


def override_sources():
    out = []
    for name in sorted(os.listdir(OVERRIDE_DIR)):
        if name.endswith(".c"):
            out.append(os.path.join(OVERRIDE_DIR, name))
    return out


def check_return_values(ovr):
    """Every override must either DEFER to the original or write C->eax.

    An override that does neither hands the caller whatever the previous call
    left in EAX. That is not hypothetical: the DirectX-check override was
    documented and written as `void`, the caller does `TEST AL,AL` on it, and
    the game branched on leftover register contents -- a silent exit(0) before
    the first frame, intermittent, and blamed in turn on backgrounding, on
    scheduling and on a lock (issue #54, C158).

    This cannot tell whether the value is RIGHT -- only the call site can, and
    Ghidra typed that one `void` too. What it can do is catch an override that
    returns nothing at all, which is the shape the defect took.
    """
    files = override_sources()
    if not files:
        return ["%s holds no .c files, so NO override body could be checked"
                % OVERRIDE_DIR]
    src = "\n".join(open(f).read() for f in files)
    bad = []
    for mod, ep, sym, rv in ovr:
        name = "__wrap_" + sym
        i = src.find(name)
        if i < 0:
            bad.append("%s has no __wrap_ body in any of the %d file(s) under "
                       "%s" % (sym, len(files), OVERRIDE_DIR))
            continue
        # the body: from the opening brace to the matching close, counted
        j = src.find("{", i)
        depth, k = 0, j
        while k < len(src):
            if src[k] == "{":
                depth += 1
            elif src[k] == "}":
                depth -= 1
                if depth == 0:
                    break
            k += 1
        body = src[j:k]
        if rv == "void":
            # Declared void: every call site was checked to overwrite EAX
            # before reading it, and the justification is in `why`. The check
            # is not switched off -- an override that forgets to declare this
            # still fails, which is the case the gate exists for.
            continue
        if "C->eax" not in body and ("__real_" + sym) not in body:
            bad.append("%s writes no return value and does not defer to "
                       "__real_%s -- its caller would read leftover EAX"
                       % (sym, sym))
    return bad


def main(argv):
    check = "--check" in argv
    ovr = load()

    by_mod = {}
    for mod, ep, sym, rv in ovr:
        by_mod.setdefault(mod, []).append(ep)

    # Oracle probes need the SAME isolation, for the same reason: their hooks
    # are also ld --wrap, and a probed function sharing a chunk with its caller
    # is bound at compile time and never records. Read from tools/probes.json
    # here rather than written by gen_probes.py, so exactly ONE program writes
    # the isolate files and the two sets cannot overwrite each other.
    n_probe = 0
    try:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        import gen_probes
        for mod, ep in gen_probes.isolate_eps():
            if ep not in by_mod.setdefault(mod, []):
                by_mod[mod].append(ep)
                n_probe += 1
    except ImportError:
        print("gen_overrides: tools/gen_probes.py is missing, so NO probe was "
              "isolated. Any declared probe will link and never fire.",
              file=sys.stderr)
        return 2

    cmake = render_cmake(ovr)
    stale = []

    if check:
        cur = open(CMAKE_OUT).read() if os.path.exists(CMAKE_OUT) else None
        if cur != cmake:
            stale.append(CMAKE_OUT)
    else:
        os.makedirs(os.path.dirname(CMAKE_OUT), exist_ok=True)
        with open(CMAKE_OUT, "w") as f:
            f.write(cmake)

    for mod, eps in by_mod.items():
        path = os.path.join(ISOLATE_DIR, mod + ".isolate")
        body = "".join("0x%08x\n" % e for e in sorted(eps))
        if check:
            cur = open(path).read() if os.path.exists(path) else None
            if cur != body:
                stale.append(path)
        else:
            os.makedirs(ISOLATE_DIR, exist_ok=True)
            with open(path, "w") as f:
                f.write(body)

    if check:
        stale += check_return_values(ovr)
        if stale:
            print("gen_overrides: STALE or missing: %s" % ", ".join(stale))
            print("  Run tools/gen_overrides.py and re-emit the affected "
                  "module(s), or the overrides will not fire.")
            return 1
        print("gen_overrides: generated wiring is up to date (%d override(s))"
              % len(ovr))
        return 0

    if n_probe:
        print("gen_overrides: %d oracle probe(s) from tools/probes.json were "
              "isolated alongside the override(s)." % n_probe)

    if not ovr:
        print("gen_overrides: NO overrides are declared. Wrote an empty "
              "%s so the build still defines RECOMP_OVERRIDE_WRAPS."
              % os.path.relpath(CMAKE_OUT, ROOT))
        return 0

    print("gen_overrides: %d override(s)" % len(ovr))
    for mod, ep, sym, rv in ovr:
        print("    %-10s 0x%08x  %s" % (mod, ep, sym))
    print("  wrote %s" % os.path.relpath(CMAKE_OUT, ROOT))
    for mod in sorted(by_mod):
        print("  wrote %s  (%d ep) -- re-emit with: python3 tools/recomp.py "
              "emit scratch/recomp/%s.json src/recomp/%s.c --split 1500 "
              "--isolate scratch/recomp/%s.isolate"
              % (os.path.relpath(os.path.join(ISOLATE_DIR, mod + ".isolate"),
                                 ROOT), len(by_mod[mod]), mod, mod, mod))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
