#!/usr/bin/env python3
"""Generate a tracing proxy DLL for one libIG*.dll.

Every export is still reachable, but a chosen subset is routed through a naked
asm thunk that records the call and then jumps to the original implementation.
The thunk is signature-agnostic on purpose: we do not know the argument counts
or calling conventions of most of these MSVC C++ methods, and a `jmp` after a
pushal/popal pair preserves the stack, ECX (`this` for __thiscall) and the
return address exactly, so the original sees a byte-identical call frame.

Why not C functions: forwarding in C requires knowing each signature. Getting
one wrong corrupts the stack silently. The asm thunk cannot get it wrong.

  gen_trace.py <orig.dll> <fwdname> <symbols-file> <outdir>

<symbols-file> is one mangled name per line -- the symbols to trace. Any name
in it that the DLL does not export, or that is a DATA export (a vftable or a
static member cannot be jumped to), is reported on stderr and left as a plain
forwarder rather than silently dropped.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pe import PE


def main(argv):
    if len(argv) != 4:
        sys.exit(__doc__)
    dll, fwd, symfile, outdir = argv
    if fwd.lower().endswith(".dll"):
        fwd = fwd[:-4]
    pe = PE(dll)
    exports = pe.exports()
    if exports is None:
        sys.exit("gen_trace: %s has no export directory" % dll)
    kind_of = {name: kind for _, _, kind, name, _ in exports if name}

    if not os.path.isfile(symfile):
        sys.exit("gen_trace: symbol file %s missing -- traced NOTHING" % symfile)
    wanted = [line.strip() for line in open(symfile) if line.strip()
              and not line.startswith("#")]
    if not wanted:
        sys.exit("gen_trace: %s is empty -- traced NOTHING" % symfile)

    traced, skipped = [], []
    for s in wanted:
        k = kind_of.get(s)
        if k is None:
            skipped.append((s, "not exported by %s" % os.path.basename(dll)))
        elif k != "CODE":
            skipped.append((s, "is a %s export, cannot be thunked" % k))
        else:
            traced.append(s)

    os.makedirs(outdir, exist_ok=True)
    base = os.path.basename(dll)

    # ---- .def: traced names alias our thunks, everything else forwards.
    with open(os.path.join(outdir, "trace.def"), "w") as f:
        f.write("LIBRARY %s\nEXPORTS\n" % base)
        tset = set(traced)
        for _, _, kind, name, _ in exports:
            if name is None:
                continue
            if name in tset:
                f.write('  "%s" = x2_thunk_%d\n' % (name, traced.index(name)))
            else:
                f.write('  "%s" = "%s.%s"%s\n'
                        % (name, fwd, name, " DATA" if kind == "DATA" else ""))

    # ---- .S: one naked thunk per traced symbol.
    with open(os.path.join(outdir, "thunks.S"), "w") as f:
        f.write("\t.text\n")
        for i, _name in enumerate(traced):
            f.write(
                "\t.globl _x2_thunk_%d\n"
                "_x2_thunk_%d:\n"
                "\tpushal\n"                    # save all GPRs incl. ECX(this)
                "\tpushfl\n"
                "\tpushl $%d\n"
                "\tcall _x2_trace_hit\n"
                "\taddl $4, %%esp\n"
                "\tpopfl\n"
                "\tpopal\n"
                "\tjmp *(_x2_real+%d)\n\n" % (i, i, i, i * 4))

    # ---- .c: resolver + the single logging call site.
    with open(os.path.join(outdir, "trace.c"), "w") as f:
        f.write(TRACE_C_HEAD)
        f.write("const char *const x2_names[%d] = {\n" % max(len(traced), 1))
        for name in traced:
            f.write('  "%s",\n' % name)
        if not traced:
            f.write('  0,\n')
        f.write("};\n")
        f.write("const int x2_count = %d;\n" % len(traced))
        f.write("void *x2_real[%d];\n" % max(len(traced), 1))
        f.write(TRACE_C_BODY % fwd)

    print("gen_trace: %d of %d requested symbols traced; %d left as plain "
          "forwarders" % (len(traced), len(wanted), len(skipped)),
          file=sys.stderr)
    for s, why in skipped:
        print("  NOT TRACED: %s -- %s" % (s, why), file=sys.stderr)


TRACE_C_HEAD = '''/* generated by tools/gen_trace.py -- do not edit */
#include <windows.h>
#include <stdio.h>

extern const char *const x2_names[];
extern const int x2_count;
extern void *x2_real[];

'''

TRACE_C_BODY = '''
static FILE *g_log;
static long  g_hits[4096];

/* Single logging call site for the whole shim. Gated by X2_TRACE: unset means
   resolve-and-forward with no output at all. X2_TRACE=<path> writes there. */
void __cdecl x2_trace_hit(int idx)
{
  if (!g_log || idx < 0 || idx >= x2_count) return;
  /* Log the first hit of each symbol plus every 1000th after, so a hot call
     cannot bury the first call of a cold one. Counting by novelty, not by a
     flat cap that would show only whatever happens to fire first. */
  long n = ++g_hits[idx];
  if (n == 1 || n %% 1000 == 0)
    fprintf(g_log, "%%8ld %%s\\n", n, x2_names[idx]);
}

static void x2_summary(void)
{
  int i, called = 0;
  if (!g_log) return;
  for (i = 0; i < x2_count; i++) if (g_hits[i]) called++;
  fprintf(g_log, "-- %%d of %%d traced symbols were called; the other %%d were "
                 "NOT reached in this run\\n", called, x2_count, x2_count - called);
  for (i = 0; i < x2_count; i++)
    if (!g_hits[i]) fprintf(g_log, "   never called: %%s\\n", x2_names[i]);
  fflush(g_log);
}

BOOL WINAPI DllMain(HINSTANCE h, DWORD reason, LPVOID reserved)
{
  int i;
  HMODULE orig;
  char path[MAX_PATH];
  (void)h; (void)reserved;
  if (reason == DLL_PROCESS_DETACH) { x2_summary(); return TRUE; }
  if (reason != DLL_PROCESS_ATTACH) return TRUE;

  orig = LoadLibraryA("%s.dll");
  if (!orig) return FALSE;            /* fail loudly: no silent half-shim */
  for (i = 0; i < x2_count; i++) {
    x2_real[i] = (void *)GetProcAddress(orig, x2_names[i]);
    if (!x2_real[i]) return FALSE;    /* an unresolved thunk would jump to 0 */
  }
  if (GetEnvironmentVariableA("X2_TRACE", path, sizeof path)) {
    g_log = fopen(path, "w");
    if (g_log) {
      fprintf(g_log, "-- tracing %%d symbols\\n", x2_count);
      setvbuf(g_log, NULL, _IOLBF, 0);
    }
  }
  return TRUE;
}
'''

if __name__ == "__main__":
    main(sys.argv[1:])
