#!/usr/bin/env python3
"""Validate the button-glyph manifest and generate its C codepoint header."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "assets" / "buttons" / "glyphs.json"


def load() -> tuple[int, list[str]]:
    data = json.loads(MANIFEST.read_text())
    first, icons = data.get("first_codepoint"), data.get("icons")
    if not isinstance(first, int) or not isinstance(icons, list):
        raise ValueError("first_codepoint must be an integer and icons must be a list")
    if len(icons) != 11 or len(set(icons)) != len(icons):
        raise ValueError(f"needs 11 unique icon names, found {len(icons)} / {len(set(icons))}")
    bad = [name for name in icons
           if not isinstance(name, str) or not re.fullmatch(r"btn_[a-z0-9]+", name)]
    if bad:
        raise ValueError(f"invalid icon name(s): {bad!r}")
    missing = [name for name in icons
               if not (MANIFEST.parent / f"{name}.svg").is_file()]
    if missing:
        raise ValueError(f"manifest SVG(s) missing: {missing!r}")
    if first < 0 or first + len(icons) > 256:
        raise ValueError("glyph codepoints do not fit in the game's one-byte font")
    return first, icons


FIRST_CODEPOINT, ICONS = load()


def emit_header(path: Path) -> None:
    lines = ["/* Generated by tools/pad_glyph_manifest.py; do not edit. */",
             "#ifndef X2_PAD_GLYPH_CODES_H", "#define X2_PAD_GLYPH_CODES_H", ""]
    for index, name in enumerate(ICONS):
        macro = "X2_PAD_GLYPH_" + name.removeprefix("btn_").upper()
        lines.append(f"#define {macro:<27} 0x{FIRST_CODEPOINT + index:02X}u")
    lines.extend(["", "#endif /* X2_PAD_GLYPH_CODES_H */", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="ascii")
    print(f"generated {path} with {len(ICONS)} glyph codepoint(s)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--selftest", action="store_true")
    parser.add_argument("--emit-header", type=Path)
    args = parser.parse_args()
    if args.selftest:
        print(f"pad glyph manifest: {len(ICONS)} SVGs, bytes "
              f"0x{FIRST_CODEPOINT:02x}..0x{FIRST_CODEPOINT + len(ICONS) - 1:02x}")
        return 0
    if not args.emit_header:
        parser.error("choose --selftest or --emit-header; generated NOTHING")
    emit_header(args.emit_header)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
