#!/usr/bin/env python3
"""Re-run the optional Xbox lift: disassembly, categorisation, then recompilation."""

from __future__ import annotations

from collections import deque
from contextlib import contextmanager
from datetime import datetime
import fcntl
import json
import os
from pathlib import Path
import subprocess
import sys
from typing import Iterator


ROOT = Path(__file__).resolve().parents[1]


def configured_path(name: str, default: Path) -> Path:
    value = os.environ.get(name)
    path = Path(value).expanduser() if value else default
    return path if path.is_absolute() else (ROOT / path).resolve()


def require_file(path: Path) -> None:
    if path.is_file():
        return
    raise SystemExit(
        f"xbox_relift: required input missing: {path}\n"
        "  Nothing was lifted. Set XBE=/path/to/default.xbe if it lives elsewhere."
    )


@contextmanager
def exclusive_lock(path: Path, label: str) -> Iterator[None]:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a+", encoding="utf-8") as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            lock.seek(0)
            holder = lock.read().strip() or "<lock held but unnamed>"
            raise SystemExit(
                f"xbox_relift: another {label} is already running (holder: {holder}).\n"
                "  Nothing was lifted. Two lifts overwrite each other's generated C."
            ) from None
        lock.seek(0)
        lock.truncate()
        lock.write(f"pid {os.getpid()} started {datetime.now().astimezone().isoformat()}\n")
        lock.flush()
        yield


def discovery_is_running(path: Path) -> bool:
    if not path.exists():
        return False
    with path.open("a+", encoding="utf-8") as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            lock.seek(0)
            holder = lock.read().strip() or "<lock held but unnamed>"
            raise SystemExit(
                "xbox_relift: a discovery loop is running "
                f"(holder: {holder}).\n"
                "  Nothing was lifted. It owns the generated C and build directory; "
                "lifting under it corrupts its next round."
            ) from None
    return False


def run_stage(command: list[str], *, cwd: Path, log: Path, tail_lines: int) -> int:
    recent: deque[str] = deque(maxlen=tail_lines)
    with log.open("w", encoding="utf-8") as destination:
        process = subprocess.Popen(command, cwd=cwd, text=True,
                                   stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        assert process.stdout is not None
        for line in process.stdout:
            destination.write(line)
            recent.append(line)
        status = process.wait()
    for line in recent:
        print(line, end="")
    return status


def seed_entries(path: Path) -> list[dict[str, object]]:
    entries = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(entries, list):
        raise SystemExit(f"xbox_relift: seeds must be a JSON list: {path}")
    return entries


def write_override_wraps(overrides: Path, generated: Path) -> None:
    entries = json.loads(overrides.read_text(encoding="utf-8"))
    if not isinstance(entries, list):
        raise SystemExit(f"xbox_relift: overrides must be a JSON list: {overrides}")
    lines = [
        "# GENERATED by tools/xbox_relift.py from xbox/overrides.json -- do not edit.",
        "#",
        "# Each function is emitted alone by `recomp --isolate`: linker --wrap only",
        "# intercepts calls crossing object files, so hand-maintaining this list would",
        "# desynchronise it from isolation and silently disable an override.",
        "",
        "set(RECOMP_OVERRIDE_WRAPS",
    ]
    missing: list[tuple[str, str]] = []
    for entry in entries:
        try:
            address = int(str(entry["start"]), 16)
        except (KeyError, TypeError, ValueError) as error:
            raise SystemExit(f"xbox_relift: invalid override entry: {entry!r}") from error
        name = str(entry.get("name", "?"))
        symbol = f"sub_{address:08X}"
        if not (generated / f"recomp_iso_{address:08X}.c").is_file():
            missing.append((symbol, name))
        lines.append(f"    -Wl,--wrap={symbol}   # {name}")
    lines.append(")")
    lines.append("")
    output = generated / "recomp_overrides.cmake"
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"xbox_relift: {len(entries)} override(s) -> {output.name}")
    if not missing:
        return
    for symbol, name in missing:
        print("xbox_relift: OVERRIDE NOT ISOLATED: "
              f"{symbol} ({name}) -- no recomp_iso_*.c was emitted, so --wrap will NOT fire",
              file=sys.stderr)
    raise SystemExit(1)


def verify_seed_dispatch(entries: list[dict[str, object]], generated: Path) -> None:
    dispatch = generated / "recomp_dispatch.c"
    if not dispatch.is_file():
        raise SystemExit(f"xbox_relift: recomp did not create dispatch table: {dispatch}")
    dispatch_text = dispatch.read_text(encoding="utf-8", errors="replace").casefold()
    runtime_missing = False
    harvested_missing = 0
    print("\nxbox_relift: seeded addresses now in the dispatch table:")
    for entry in entries:
        try:
            address = int(str(entry["start"]), 16)
        except (KeyError, TypeError, ValueError) as error:
            raise SystemExit(f"xbox_relift: invalid seed entry: {entry!r}") from error
        source = str(entry.get("source", "observed"))
        if f"0x{address:08x}" in dispatch_text:
            continue
        if source == "harvest":
            print(f"  0x{address:08X}  not a function (harvested candidate, no match)")
            harvested_missing += 1
            continue
        print(f"  0x{address:08X}  MISSING -- a RUNTIME-OBSERVED seed did not land",
              file=sys.stderr)
        runtime_missing = True
    print(f"xbox_relift: {len(entries)} seeds, {harvested_missing} harvested candidates "
          "did not resolve to a function")
    if runtime_missing:
        raise SystemExit("xbox_relift: a runtime-observed seed did not land.")


def main() -> int:
    xboxrecomp = ROOT / "vendor/xboxrecomp"
    xbe = configured_path("XBE", xboxrecomp / "game_files/default.xbe")
    seeds = configured_path("SEEDS", ROOT / "xbox/seeds.json")
    overrides = configured_path("OVERRIDES", ROOT / "xbox/overrides.json")
    generated = configured_path("GEN_DIR", ROOT / "xbox/src/recomp/gen")
    logs = configured_path("LOG_DIR", ROOT / "scratch/logs")
    for required in (xbe, seeds, overrides):
        require_file(required)
    if not xboxrecomp.is_dir():
        raise SystemExit(f"xbox_relift: maintained xboxrecomp fork is missing: {xboxrecomp}")
    logs.mkdir(parents=True, exist_ok=True)
    generated.mkdir(parents=True, exist_ok=True)
    entries = seed_entries(seeds)
    with exclusive_lock(ROOT / "scratch/.xbox_lift.lock", "lift"):
        if not os.environ.get("XBOX_DISCOVER_PID"):
            discovery_is_running(ROOT / "scratch/.xbox_discover.lock")
        print(f"xbox_relift: XBE={xbe}")
        print(f"xbox_relift: seeding {len(entries)} runtime-discovered function(s) from {seeds}")
        tests = [sys.executable, "-m", "pytest", "tools/recomp/test_lifter.py",
                 "tools/recomp/test_regressions.py", "-q"]
        print("== 0/3 recompiler tests ==")
        if run_stage(tests, cwd=xboxrecomp, log=logs / "xbox_relift_tests.log", tail_lines=5):
            print("xbox_relift: RECOMPILER TESTS FAILED -- not lifting.", file=sys.stderr)
            print("  Set SKIP_TESTS=1 to lift anyway (and expect the result to be wrong).",
                  file=sys.stderr)
            if os.environ.get("SKIP_TESTS") != "1":
                return 1
        print("== 1/3 disasm (function detection) ==")
        if run_stage([sys.executable, "-m", "tools.disasm", str(xbe), "--force",
                      "--seed-functions", str(seeds)], cwd=xboxrecomp,
                     log=logs / "xbox_relift_disasm.log", tail_lines=20):
            return 1
        print("== 2/3 func_id (categorisation) ==")
        if run_stage([sys.executable, "-m", "tools.func_id", str(xbe)], cwd=xboxrecomp,
                     log=logs / "xbox_relift_funcid.log", tail_lines=10):
            return 1
        print("== 3/3 recomp (x86 -> C) ==")
        if run_stage([sys.executable, "-m", "tools.recomp", str(xbe), "--all", "--split", "1000",
                      "--isolate", str(overrides), "--gen-dir", str(generated)], cwd=xboxrecomp,
                     log=logs / "xbox_relift_recomp.log", tail_lines=20):
            return 1
        write_override_wraps(overrides, generated)
        verify_seed_dispatch(entries, generated)
    print("xbox_relift: done. Rebuild with: cmake --build <build-dir>")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
